services:
  backend:
    image: tool-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tool-marketing-backend
    restart: always
    expose:
      - "8001"
    ports:
      - "8002:8001"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - tool-network

  frontend:
    image: tool-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tool-marketing-frontend
    restart: always
    ports:
      - "8001:80"
      - "5173:80"
    depends_on:
      - backend
    networks:
      - tool-network

networks:
  tool-network:
    driver: bridge
